// @ts-check
/**
 * The documentation, held to the code.
 *
 * `CLAUDE.md` and `README.md` carried ten falsifiable errors between them, and
 * the expensive ones were not opinions — they were paths. Five rows of the
 * endpoint table named routes that return 404 (`/v1/score`, `/v1/taxonomy`,
 * `/v1/pcaf`, `/v1/covenant`, `/v1/webhook` are all project-scoped or plural
 * in the router), so a reader following the table got a 404 from the first
 * four things they tried. Part A was described as "planned, not built" over
 * 3,271 routed lines. Firestore was named throughout where the code calls
 * `admin.database()`, which is the Realtime Database. `services/` was cited
 * twice and has not existed since the domains split.
 *
 * Prose drifts and nothing can stop it. A **path** is checkable, and so is a
 * directory, and so is a count — so those are checked. In fairness to the
 * documents, 131 of 132 cited file paths already resolved: the drift was in
 * tables and in claims, which is what this covers.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

/** Comments stripped, so a note *about* the old shape does not read as the old shape. */
const withoutComments = text => text.replace(/^\s*#.*$/gm, '');

/**
 * A sentence that is *recording* an error rather than making it.
 *
 * These documents describe the corrections they carry — "Firestore was named
 * throughout where the code calls `admin.database()`" is the fix, not the
 * fault. This is the same shape as the language guard letting "**not**
 * approved, endorsed or certified by PCAF" through: the marker is what makes
 * the sentence a correction, and a sweep that cannot see it flags its own
 * changelog. Third instance of this trap in this repository.
 */
const RETROSPECTIVE = /\b(was|were|used to|no longer|has not existed|does not exist|stopped|removed|instead of|rather than|not Firestore|used|previously|until|old|former|corrected|fails the build|sweeps? for|refuses)\b/i;

/** Split into sentences, keeping a wrapped paragraph as one. */
const sentences = md => md.replace(/\n(?!\n)/g, ' ').split(/(?<=[.!?])\s+/);

const CLAUDE = read('CLAUDE.md');
const README = read('README.md');
const openapi = JSON.parse(read('docs/openapi.json'));

/** Every path the router serves, as the document records it. */
const SERVED = new Set(Object.keys(openapi.paths));

/** `/v1/partc/projects/{id}` and `/v1/partc/projects/:id` are the same route. */
const normalise = p => p.replace(/\{[^}]+\}/g, ':x').replace(/:[A-Za-z0-9_]+/g, ':x').replace(/\/$/, '');
const SERVED_SHAPES = new Set([...SERVED].map(normalise));

/** The `/v1/…` paths a markdown table's Endpoint column names. */
function tablePaths(md) {
  const out = new Set();
  for (const m of md.matchAll(/^\|[^|\n]*\|\s*`([^`]+)`\s*(?:·\s*`([^`]+)`\s*)?\|/gm)) {
    for (const cell of [m[1], m[2]]) {
      if (!cell) continue;
      for (const p of cell.split('·').map(x => x.trim())) {
        if (p.startsWith('/v1/') || p === '/health' || p === '/v1') out.add(p);
      }
    }
  }
  return [...out];
}

describe('Every path a document names is one the router serves', () => {
  test('CLAUDE.md', () => {
    const missing = tablePaths(CLAUDE).filter(p => {
      /* A row may name a sibling suffix — `/v1/baselines/:id/release` · `/supersede`.
         The leading path is the one to check; a bare suffix is resolved against it. */
      if (!p.startsWith('/')) return false;
      return !SERVED_SHAPES.has(normalise(p));
    });
    expect(missing).toEqual([]);
  });

  test('README.md — and its table is generated, so it cannot be otherwise', () => {
    const missing = tablePaths(README).filter(p => p.startsWith('/') && !SERVED_SHAPES.has(normalise(p)));
    expect(missing).toEqual([]);
    expect(README).toContain('<!-- BEGIN ENDPOINTS — generated by npm run docs:readme -->');
  });

  test('the README states the real size of the surface', () => {
    const total = Object.keys(openapi.paths).reduce((n, p) =>
      n + Object.keys(openapi.paths[p]).filter(m => ['get', 'post', 'put', 'patch', 'delete'].includes(m)).length, 0);
    expect(README).toContain(`_${total} operations across ${Object.keys(openapi.paths).length} paths.`);
  });
});

describe('Claims that were falsifiable, and false', () => {
  test('Part A is not described as unbuilt while it is routed', () => {
    /* 3,271 lines and two live routes. */
    expect(fs.existsSync(path.join(ROOT, 'src/domains/pcaf-part-a/domain/attribution.js'))).toBe(true);
    expect(SERVED.has('/v1/pcaf/part-a/assess')).toBe(true);
    expect(CLAUDE).not.toMatch(/Part A \(financed emissions\) — planned, not built/);
  });

  test('the store is named as what the code calls', () => {
    /* `admin.database()` is the Realtime Database. Firestore is a different
       product, and a developer told to open the Firestore console will not
       find the data. */
    const fb = read('src/platform/bridge/firebase.js');
    expect(fb).toMatch(/admin\.database\(\)/);
    expect(fb).not.toMatch(/admin\.firestore\(\)/);
    for (const [name, md] of [['CLAUDE.md', CLAUDE], ['README.md', README]]) {
      /* It may be named, but only to say it is not what this uses — or to
         record that it once was. */
      const wrong = sentences(md).filter(x => /Firestore/.test(x) && !RETROSPECTIVE.test(x));
      expect({ file: name, wrong }).toEqual({ file: name, wrong: [] });
    }
  });

  test('no document cites a top-level directory the split removed', () => {
    const gone = ['services', 'routes', 'middleware', 'models', 'schemas'];
    for (const d of gone) expect(fs.existsSync(path.join(ROOT, d))).toBe(false);

    const cited = [];
    for (const [name, md] of [['CLAUDE.md', CLAUDE], ['README.md', README], ['CONTRIBUTING.md', read('CONTRIBUTING.md')]]) {
      for (const sentence of sentences(md)) {
        if (RETROSPECTIVE.test(sentence)) continue;   // recording it, not citing it
        for (const d of gone) {
          /* In a backtick span, at the start of a path.
             `src/domains/…/schemas/` is fine; a bare `schemas/` is the one the
             split removed. */
          const re = new RegExp('`' + d + '/', 'g');
          for (const _m of sentence.matchAll(re)) cited.push(`${name}: \`${d}/\``);
        }
      }
    }
    expect(cited).toEqual([]);
  });

  test('the test counts a document states are the counts the suite has', () => {
    /* "26 tests across 6 suites" was in the README against an actual 117 and
       2,373. A number in a document is a claim like any other. */
    const suites = fs.readdirSync(path.join(ROOT, 'tests')).filter(f => f.endsWith('.test.js')).length;
    for (const md of [README, CLAUDE]) {
      for (const m of md.matchAll(/(\d[\d,]*)\s+suites?,\s*([\d,]+)\s+tests/g)) {
        const stated = Number(m[1].replace(/,/g, ''));
        /* Within a suite or two — a document is allowed to be rounded, not
           wrong by an order of magnitude. */
        expect(Math.abs(stated - suites)).toBeLessThanOrEqual(3);
      }
    }
  });
});

describe('The governance pack exists', () => {
  test.each([
    'CONTRIBUTING.md',
    'SECURITY.md',
    'CODEOWNERS',
    'CHANGELOG.md',
    'LICENSE',
    '.github/pull_request_template.md',
    '.github/ISSUE_TEMPLATE/bug.md',
    '.github/ISSUE_TEMPLATE/change.md',
    '.nvmrc',
    '.editorconfig',
    'docs/CODE-TOUR.md',
    'docs/GLOSSARY.md',
    'docs/adr/README.md',
  ])('%s', f => {
    expect(fs.existsSync(path.join(ROOT, f))).toBe(true);
    /* A floor, so an empty placeholder does not pass as a governance file.
       `.nvmrc` is two bytes and is exempt by being a version, not prose. */
    const floor = /^\.(nvmrc)$/.test(f) ? 1 : 40;
    expect(read(f).trim().length).toBeGreaterThanOrEqual(floor);
  });

  test('every ADR the index lists exists, and every ADR is indexed', () => {
    const index = read('docs/adr/README.md');
    const files = fs.readdirSync(path.join(ROOT, 'docs/adr'))
      .filter(f => /^\d{4}-.*\.md$/.test(f)).sort();
    expect(files.length).toBeGreaterThan(4);
    for (const f of files) expect(index).toContain(f);
    for (const m of index.matchAll(/\((\d{4}-[a-z0-9-]+\.md)\)/g)) {
      expect(fs.existsSync(path.join(ROOT, 'docs/adr', m[1]))).toBe(true);
    }
  });

  test('each ADR says what went wrong, not only what was decided', () => {
    /* A record that omits the failure is a record the next person overturns,
       because the reasoning looks like taste until you know what it cost. */
    for (const f of fs.readdirSync(path.join(ROOT, 'docs/adr')).filter(x => /^\d{4}-/.test(x))) {
      const md = read(`docs/adr/${f}`);
      expect({ f, has: /## Context/.test(md) }).toEqual({ f, has: true });
      expect({ f, has: /## Decision/.test(md) }).toEqual({ f, has: true });
      expect({ f, has: /## Consequences/.test(md) }).toEqual({ f, has: true });
      expect({ f, status: /\*\*Status:\*\* (accepted|superseded|reversed)/.test(md) })
        .toEqual({ f, status: true });
    }
  });
});

describe('One Node version, in every place that declares one', () => {
  test('.nvmrc, package.json engines, the Dockerfile, CI and Netlify agree', () => {
    /* It was declared four times and disagreed with itself: `>=18`, a
       `node:18-alpine` image, a CI matrix of 20 and 22, and a function runtime
       of nodejs22.x. */
    const nvmrc = read('.nvmrc').trim();
    expect(nvmrc).toMatch(/^\d+$/);

    const engines = JSON.parse(read('package.json')).engines.node;
    expect(engines).toBe(`>=${nvmrc}.0.0`);

    expect(read('docker/Dockerfile')).toContain(`FROM node:${nvmrc}-alpine`);
    expect(read('netlify.toml')).toContain(`NODE_VERSION = "${nvmrc}"`);

    const ci = read('.github/workflows/fintech-ci.yml');
    const matrix = (ci.match(/node-version: \[([^\]]+)\]/) || [])[1] || '';
    expect(matrix.split(',').map(x => x.trim())).toContain(nvmrc);
  });
});

describe('The local stack can be started from a fresh clone', () => {
  const compose = read('docker/docker-compose.yml');

  test('it does not require a .env the clone does not have', () => {
    /* `env_file: ../.env` is required by default, so `docker compose config`
       failed outright before any service started. */
    expect(compose).toMatch(/required:\s*false/);
  });

  test('it runs a path that exists', () => {
    /* Comments stripped first. The file explains the defect it fixed, and a
       sweep that reads its own explanation as the defect is the trap this
       repository has fallen into twice. */
    expect(withoutComments(compose)).not.toMatch(/node --watch server\.js/);
    expect(fs.existsSync(path.join(ROOT, 'src/server.js'))).toBe(true);
  });

  test('it models the store the application actually uses', () => {
    /* The only backing service was a Firebase emulator, while every
       deployment holds its records in PostgreSQL. */
    expect(compose).toMatch(/image:\s*postgres:/);
    expect(compose).toMatch(/DATABASE_URL/);
  });

  test('the image can run the checks, not only the server', () => {
    /* `npm ci --production` omits devDependencies, so the container had no
       jest, no eslint and no tsc. */
    const dockerfile = read('docker/Dockerfile');
    expect(dockerfile).toMatch(/AS dev/);
    expect(dockerfile).toMatch(/RUN npm ci\s*$/m);
  });
});

describe('The destructive command is guarded', () => {
  const seed = require('../scripts/seed-demo-data');

  test('it names what it will delete, and refuses without confirmation', () => {
    const out = [];
    const log = console.log; const err = console.error;
    console.log = m => out.push(String(m)); console.error = m => out.push(String(m));
    let verdict;
    try { verdict = seed.guardClear(['--clear']); } finally { console.log = log; console.error = err; }

    expect(verdict.proceed).toBe(false);
    expect(verdict.code).toBe(1);
    const text = out.join('\n');
    for (const p of seed.CLEARED_PATHS) expect(text).toContain(p);
    expect(text).toMatch(/--dry-run/);
    expect(text).toMatch(/--yes I-understand/);
  });

  test('--dry-run deletes nothing and exits clean', () => {
    const log = console.log; const err = console.error;
    console.log = () => {}; console.error = () => {};
    let verdict;
    try { verdict = seed.guardClear(['--clear', '--dry-run']); } finally { console.log = log; console.error = err; }
    expect(verdict).toEqual({ proceed: false, code: 0 });
  });

  test('confirmed, it proceeds', () => {
    const log = console.log; const err = console.error;
    console.log = () => {}; console.error = () => {};
    let verdict;
    try { verdict = seed.guardClear(['--clear', '--yes', 'I-understand']); } finally { console.log = log; console.error = err; }
    expect(verdict.proceed).toBe(true);
  });

  test('it refuses outright in production, confirmed or not', () => {
    const was = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    const log = console.log; const err = console.error;
    console.log = () => {}; console.error = () => {};
    let verdict;
    try { verdict = seed.guardClear(['--clear', '--yes', 'I-understand']); }
    finally { console.log = log; console.error = err; process.env.NODE_ENV = was; }
    expect(verdict).toEqual({ proceed: false, code: 1 });
  });

  test('it removes a named list, never a prefix', () => {
    /* A `remove()` on `fintech` would take the API keys, the accounts and the
       audit chain with it, and the difference is one string. */
    for (const p of seed.CLEARED_PATHS) expect(p.split('/').length).toBeGreaterThan(1);
    expect(seed.CLEARED_PATHS).not.toContain('fintech');
  });
});

describe('The code tour’s generated blocks are current', () => {
  const tour = read('docs/CODE-TOUR.md');
  const { COLLECTIONS } = require('../src/platform/database/collections');

  test('every table is in the diagram', () => {
    for (const def of Object.values(COLLECTIONS)) expect(tour).toContain(`  ${def.table} {`);
  });

  test('every foreign key is an edge', () => {
    for (const [name, def] of Object.entries(COLLECTIONS)) {
      for (const parent of def.dependsOn || []) {
        expect(tour).toContain(`${COLLECTIONS[parent].table} ||--o{ ${COLLECTIONS[name].table}`);
      }
    }
  });

  test('it carries the request lifecycle and the module map', () => {
    expect(tour).toMatch(/sequenceDiagram/);
    expect(tour).toMatch(/flowchart TD/);
    expect(tour).toContain('<!-- BEGIN MODULE-MAP');
  });
});

describe('The glossary keeps the three scales apart', () => {
  const glossary = read('docs/GLOSSARY.md');

  test('it says Part A’s mapping is per asset class', () => {
    /* The single mistake most likely to produce a wrong regulatory figure. */
    expect(glossary).toMatch(/no global option→score lookup/);
    expect(glossary).toMatch(/\(asset class, option\) → score/);
  });

  test('it states the direction of the PCAF scale', () => {
    expect(glossary).toMatch(/1 is best/);
    expect(glossary).toMatch(/never a mark out of five/);
  });

  test('it keeps GCF’s tiers out of the numerals', () => {
    expect(glossary).toMatch(/measured · modelled · benchmark · declared/);
    expect(glossary).toMatch(/deliberately not numerals/);
  });

  test('it states the two weightings', () => {
    expect(glossary).toMatch(/outstanding amount.*p\.128/);
    expect(glossary).toMatch(/premium.*Box 6-3/);
  });
});
