#!/usr/bin/env node
/**
 * CarbonIQ FinTech — .env Generator
 *
 * Generates a ready-to-use .env file with secure random values.
 * Run once when setting up a new environment:
 *
 *   node scripts/generate-env.js
 *
 * Then fill in the Firebase and Anthropic values manually.
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const encryptionKey = crypto.randomBytes(32).toString('hex');
const apiKeySalt    = crypto.randomBytes(32).toString('hex');
const webhookSecret = crypto.randomBytes(24).toString('hex');
const devApiKey     = 'ck_test_' + crypto.randomBytes(16).toString('hex');

const envContent = `# ===== CarbonIQ FinTech — Environment Variables =====
# Generated by: node scripts/generate-env.js on ${new Date().toISOString()}
# NEVER commit this file to version control.

# -----------------------------------------------------------------------
# STEP 1: Firebase (Required for full functionality)
# Go to: Firebase Console → Project Settings → General → Your apps → Config
# -----------------------------------------------------------------------
FIREBASE_API_KEY=PASTE_YOUR_FIREBASE_API_KEY_HERE
FIREBASE_DATABASE_URL=https://YOUR_PROJECT_ID-default-rtdb.firebaseio.com

# Go to: Firebase Console → Project Settings → Service Accounts → Generate new private key
# Then encode it: cat your-key.json | base64 -w 0   (Linux/Mac)
#                 certutil -encode your-key.json tmp.b64 && findstr /v /c:- tmp.b64 (Windows)
FIREBASE_SERVICE_ACCOUNT=PASTE_BASE64_ENCODED_SERVICE_ACCOUNT_JSON_HERE

# -----------------------------------------------------------------------
# STEP 2: Anthropic AI (Required for BOQ extraction and AI agents)
# Go to: https://console.anthropic.com/api-keys
# -----------------------------------------------------------------------
ANTHROPIC_API_KEY=PASTE_YOUR_ANTHROPIC_API_KEY_HERE

# -----------------------------------------------------------------------
# STEP 3: Auto-generated secure values (ready to use — do not change)
# -----------------------------------------------------------------------
DATA_ENCRYPTION_KEY=${encryptionKey}
API_KEY_SALT=${apiKeySalt}
WEBHOOK_SIGNING_SECRET=${webhookSecret}

# Development bypass API key (only works when Firebase is not configured)
# Use this key in the frontend settings during local development
DEV_API_KEY=${devApiKey}

# -----------------------------------------------------------------------
# Server Configuration
# -----------------------------------------------------------------------
FINTECH_API_PORT=3001
FINTECH_API_ENABLED=true
NODE_ENV=development

# -----------------------------------------------------------------------
# CORS — add your Netlify domain here after deployment
# -----------------------------------------------------------------------
ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000,https://YOUR_NETLIFY_SITE.netlify.app

# -----------------------------------------------------------------------
# PCAF Configuration
# -----------------------------------------------------------------------
PCAF_VERSION=3.0
PCAF_DEFAULT_ATTRIBUTION=1.0

# -----------------------------------------------------------------------
# Taxonomy Versions
# -----------------------------------------------------------------------
TAXONOMY_ASEAN_VERSION=3
TAXONOMY_EU_VERSION=2024
TAXONOMY_HK_VERSION=2024

# -----------------------------------------------------------------------
# Webhook Configuration
# -----------------------------------------------------------------------
WEBHOOK_TIMEOUT_MS=5000
WEBHOOK_MAX_RETRIES=3

# -----------------------------------------------------------------------
# Feature Flags
# -----------------------------------------------------------------------
FF_COVENANT_ENGINE=true
FF_PORTFOLIO_AGGREGATION=true
FF_TAXONOMY_CHECKER=true
FF_CERTIFICATE_GENERATION=false
FF_INSURANCE_OUTPUT=false

# -----------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------
LOG_LEVEL=info
LOG_VERBOSE=false
`;

const envPath = path.join(__dirname, '..', '.env');

if (fs.existsSync(envPath)) {
  console.log('\x1b[33m⚠️  .env already exists. Writing to .env.new instead.\x1b[0m');
  fs.writeFileSync(envPath + '.new', envContent);
  console.log('Created: .env.new');
  console.log('Review it and rename to .env if you want to replace your existing config.');
} else {
  fs.writeFileSync(envPath, envContent);
  console.log('\x1b[32m✅ Created: .env\x1b[0m');
}

console.log('\n\x1b[36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m');
console.log('\x1b[36m  Next Steps:\x1b[0m');
console.log('\x1b[36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\x1b[0m');
console.log('');
console.log(' 1. Open .env and fill in Firebase values');
console.log(' 2. Fill in ANTHROPIC_API_KEY');
console.log(' 3. Run:  node scripts/verify-setup.js');
console.log(' 4. Run:  node scripts/create-api-key.js');
console.log('');
console.log('\x1b[33m  For LOCAL DEV without Firebase:\x1b[0m');
console.log(`  Use this key in the frontend:  \x1b[32m${devApiKey}\x1b[0m`);
console.log('  (Works when FIREBASE_SERVICE_ACCOUNT is not set)\n');
