// @ts-check
/**
 * The route table as the application registered it, with the scope each
 * route requires — the source of docs/API-SCOPES.md and of the test that
 * holds the document to the code.
 */

'use strict';

const { requiredScopeFor } = require('./scopes');

/** Express keeps a path's regexp; this recovers the pattern it was built from. */
function layerPath(layer) {
  if (layer.route) return layer.route.path;
  const src = layer.regexp && layer.regexp.source;
  if (!src || src === '^\\/?$' || src === '^\\/?(?=\\/|$)') return '';
  /* `^\/v1\/?(?=\/|$)` → `/v1`; parameters were compiled into groups, which
     `layer.keys` names in order. */
  let p = src
    .replace(/^\^/, '')
    .replace(/\\\/\?\(\?=\\\/\|\$\)$/, '')
    .replace(/\\\//g, '/')
    .replace(/\$$/, '');
  const keys = (layer.keys || []).map(k => k.name);
  let i = 0;
  p = p.replace(/\(\?:\(\[\^\\\/\]\+\?\)\)/g, () => `:${keys[i++] || 'param'}`);
  return p;
}

/**
 * Every registered route: method, full pattern, and its scope.
 * @param {any} app  the Express application
 */
function routeTable(app) {
  const rows = [];
  const walk = (stack, prefix) => {
    for (const layer of stack) {
      if (layer.route) {
        const full = `${prefix}${layer.route.path}`.replace(/\/{2,}/g, '/').replace(/\/$/, '') || '/';
        for (const method of Object.keys(layer.route.methods)) {
          if (method === '_all') continue;
          const m = method.toUpperCase();
          /* dualAuth (supervisor) delegates to one of the two, so it counts. */
          const authenticated = layer.route.stack.some(l => ['apiKeyAuth', 'auth', 'dualAuth'].includes(l.name));
          const { scope, why } = requiredScopeFor(m, full);
          const lockVariant = /\/status$/.test(full) && m === 'POST'
            ? requiredScopeFor(m, full, { status: 'locked' }).scope : null;
          rows.push({ method: m, path: full, scope, why, authenticated, lockVariant });
        }
      } else if (layer.handle && layer.handle.stack) {
        walk(layer.handle.stack, `${prefix}${layerPath(layer)}`);
      }
    }
  };
  walk(app._router.stack, '');
  const order = { GET: 0, POST: 1, PUT: 2, PATCH: 3, DELETE: 4, HEAD: 5, OPTIONS: 6 };
  return rows
    .filter(r => r.path.startsWith('/v1') || r.path === '/health')
    .sort((a, b) => a.path.localeCompare(b.path) || (order[a.method] ?? 9) - (order[b.method] ?? 9));
}

function renderScopesDoc(rows) {
  const lines = [];
  lines.push('# API scopes');
  lines.push('');
  lines.push('Generated by `npm run docs:scopes` from the running router and `src/platform/auth/scopes.js`.');
  lines.push('`tests/scopes.test.js` fails the build when this file no longer matches the code.');
  lines.push('');
  lines.push('| Scope | Grants |');
  lines.push('|---|---|');
  lines.push('| `read` | every GET, and the computations that store nothing |');
  lines.push('| `write` | create, change or delete a record |');
  lines.push('| `lock` | lock an assessment — it enters the disclosure |');
  lines.push('| `assess` | run an engine that persists a run or calls an AI agent |');
  lines.push('| `admin` | reserved; no route requires it yet |');
  lines.push('');
  lines.push('A key issued before scopes existed carries none: it keeps everything it could do, every response on it says');
  lines.push('`X-Key-Scopes: unscoped`, and `npm run key:list` counts them. `npm run key:scope -- <key-id> --scopes …` applies scopes.');
  lines.push('A signed-in user\'s scopes follow the role level: administrator everything; credit officer and ESG analyst read, write, lock, assess;');
  lines.push('relationship manager read, write, assess; auditor and borrower read.');
  lines.push('');
  lines.push(`${rows.length} routes.`);
  lines.push('');
  lines.push('| Method | Route | Scope | Why |');
  lines.push('|---|---|---|---|');
  for (const r of rows) {
    const scope = r.lockVariant ? `\`${r.scope}\` · \`${r.lockVariant}\` when status is locked` : `\`${r.scope}\``;
    const auth = r.authenticated ? '' : ' (no credential)';
    lines.push(`| ${r.method} | \`${r.path}\`${auth} | ${scope} | ${r.why} |`);
  }
  lines.push('');
  return lines.join('\n');
}

module.exports = { routeTable, renderScopesDoc, layerPath };
